name: Deploy to OVH

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ftp://ftp.ledodo.xyz
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /www/
